/**
 * Unit tests for the anonymize-broker-export script's pure transform function.
 *
 * The script is a CLI utility that takes a broker export's raw rows (IBKR
 * Activity Statement CSV, Revolut Account Statement xlsx/csv), strips
 * customer-identifying information, and writes a rows-JSON fixture. This test
 * exercises the pure `anonymizeBrokerRows` function in isolation; the CLI
 * wrapper (argv parsing, file IO, xlsx/csv reading) is intentionally not
 * covered here.
 *
 * The round-trip tests are the load-bearing ones: a statement generated by the
 * committed synthetic generators (the executable format specs), with PII rows
 * injected, must parse to the IDENTICAL ParseResult after anonymization. That
 * is the guarantee that anonymizing a real user sample can never change what
 * the parser sees in the cells that matter.
 */
import { describe, it, expect } from 'vitest';
import { anonymizeBrokerRows } from '../anonymize-broker-export.js';
import { parseIbkrCsv } from '../../shared/src/parsers/ibkr';
import { parseRevolutStatement } from '../../shared/src/parsers/revolut';
import { generateIbkrStatement } from '../../shared/src/parsers/__tests__/ibkrSynthetic';
import { generateRevolutStatement } from '../../shared/src/parsers/__tests__/revolutSynthetic';

function ibkrSampleRows(): string[][] {
  const rows = generateIbkrStatement({
    trades: [
      { symbol: 'AAPL', quantity: 10, price: 150, dateTime: '2025-03-10, 10:30:00', commission: 1 },
      { symbol: 'AAPL', quantity: -10, price: 180, dateTime: '2025-09-15, 14:00:00', commission: 1 },
    ],
    dividends: [
      { symbol: 'AAPL', isin: 'US0378331005', date: '15-05-25', amount: 24, withholding: 2.4 },
    ],
    instruments: [{ symbol: 'AAPL', isin: 'US0378331005', name: 'APPLE INC' }],
  });
  // The generator emits `Account Information,Data,Account,U1234567` but no Name
  // row; real statements carry one. Inject it right after the Account row, plus
  // an alias and an address, so the scrub rules face the real shape.
  const accountRowIdx = rows.findIndex((r) => r[0] === 'Account Information' && r[2] === 'Account');
  rows.splice(
    accountRowIdx + 1,
    0,
    ['Account Information', 'Data', 'Name', 'Ion Popescu'],
    ['Account Information', 'Data', 'Account Alias', 'Ion Popescu invest'],
    ['Account Information', 'Data', 'Address', 'Str. Exemplu 12, Bucuresti'],
    ['Account Information', 'Data', 'Account Type', 'Individual'],
    ['Account Information', 'Data', 'Base Currency', 'USD'],
  );
  return rows;
}

function revolutSampleRows(): string[][] {
  const rows = generateRevolutStatement({
    trades: [
      { ticker: 'MSFT', side: 'buy', quantity: 2, pricePerShare: 300, totalAmount: 600, date: '2025-02-01T10:00:00.000Z' },
      { ticker: 'MSFT', side: 'sell', quantity: 1, pricePerShare: 350, totalAmount: 350, date: '2025-08-01T10:00:00.000Z' },
    ],
    dividends: [{ ticker: 'MSFT', amount: 1.5, date: '2025-06-12T08:00:00.000Z' }],
    splits: [{ ticker: 'NVDA', quantity: 9, date: '2025-06-10T00:00:00.000Z' }],
  });
  // The synthetic generator emits the header at row 0; a real xlsx download can
  // carry a title/preamble block above it. Inject one with the PII a real
  // export could hold.
  return [
    ['Account Statement'],
    ['Ion Popescu', '', 'ion.popescu@example.com'],
    ['IBAN', 'RO49AAAA1B31007593840000'],
    ['', '', ''],
    ...rows,
  ];
}

describe('anonymizeBrokerRows: IBKR', () => {
  it('replaces the Account Information Name value and keeps the field name', () => {
    const { rows } = anonymizeBrokerRows(ibkrSampleRows(), 'ibkr');
    const nameRow = rows.find((r) => r[0] === 'Account Information' && r[2] === 'Name')!;
    expect(nameRow[3]).toBe('Anonymized User');
    expect(JSON.stringify(rows)).not.toContain('Ion Popescu');
  });

  it('replaces the account number everywhere with a consistent placeholder', () => {
    const input = ibkrSampleRows();
    // A consolidated statement can repeat the account number outside Account
    // Information; prove the global map catches it.
    input.push(['Notes/Legal Notes', 'Data', 'Statement for U1234567']);
    const { rows, replacements } = anonymizeBrokerRows(input, 'ibkr');
    const flat = JSON.stringify(rows);
    expect(flat).not.toContain('U1234567');
    const accountRow = rows.find((r) => r[0] === 'Account Information' && r[2] === 'Account')!;
    expect(accountRow[3]).toBe('U0000001');
    expect(rows[rows.length - 1][2]).toBe('Statement for U0000001');
    expect(replacements.accountIds).toBe(2);
    expect(replacements.uniqueAccountIds).toBe(1);
  });

  it('maps distinct account numbers to distinct placeholders', () => {
    const input = ibkrSampleRows();
    input.push(['Account Information', 'Data', 'Accounts', 'U1234567, U7654321']);
    const { rows, replacements } = anonymizeBrokerRows(input, 'ibkr');
    expect(rows[rows.length - 1][3]).toBe('U0000001, U0000002');
    expect(replacements.uniqueAccountIds).toBe(2);
  });

  it('scrubs alias and address values, preserves Account Type and Base Currency', () => {
    const { rows } = anonymizeBrokerRows(ibkrSampleRows(), 'ibkr');
    const byField = (name: string) =>
      rows.find((r) => r[0] === 'Account Information' && r[2] === name)!;
    expect(byField('Account Alias')[3]).toBe('anon');
    expect(byField('Address')[3]).toBe('[removed]');
    expect(byField('Account Type')[3]).toBe('Individual');
    expect(byField('Base Currency')[3]).toBe('USD');
  });

  it('never touches trades, instruments, dividends or withholding rows', () => {
    const input = ibkrSampleRows();
    const { rows } = anonymizeBrokerRows(input, 'ibkr');
    const financial = (allRows: string[][]) =>
      allRows.filter((r) => r[0] !== 'Account Information' && r[0] !== 'Statement');
    expect(financial(rows)).toEqual(financial(input));
    expect(JSON.stringify(rows)).toContain('US0378331005');
    expect(JSON.stringify(rows)).toContain('APPLE INC');
  });

  it('does not touch a bare "U" ticker (Unity) or ISINs with the global account-ID rule', () => {
    const input = ibkrSampleRows();
    input.push(['Trades', 'Data', 'Order', 'Stocks', 'USD', 'U', '2025-04-01, 10:00:00', '5', '20', '20', '-100', '0', '100', '0', '0', 'O']);
    const { rows } = anonymizeBrokerRows(input, 'ibkr');
    expect(rows[rows.length - 1][5]).toBe('U');
    expect(JSON.stringify(rows)).toContain('US0378331005');
  });

  it('round-trip: the anonymized statement parses identically to the original', () => {
    const input = ibkrSampleRows();
    const { rows } = anonymizeBrokerRows(input, 'ibkr');
    const before = parseIbkrCsv(input);
    const after = parseIbkrCsv(rows);
    expect(before.transactions.length).toBeGreaterThan(0);
    expect(after).toEqual(before);
  });
});

describe('anonymizeBrokerRows: Revolut', () => {
  it('scrubs every non-empty preamble cell above the header row', () => {
    const { rows, replacements } = anonymizeBrokerRows(revolutSampleRows(), 'revolut');
    expect(rows[0]).toEqual(['[removed]']);
    expect(rows[1]).toEqual(['[removed]', '', '[removed]']);
    expect(rows[2]).toEqual(['[removed]', '[removed]']);
    expect(rows[3]).toEqual(['', '', '']);
    const flat = JSON.stringify(rows);
    expect(flat).not.toContain('Ion Popescu');
    expect(flat).not.toContain('ion.popescu@example.com');
    expect(flat).not.toContain('RO49AAAA1B31007593840000');
    expect(replacements.preambleCells).toBe(5);
  });

  it('keeps the header row and every data row byte-identical', () => {
    const input = revolutSampleRows();
    const headerIdx = input.findIndex((r) => r.includes('Date') && r.includes('Type'));
    const { rows } = anonymizeBrokerRows(input, 'revolut');
    expect(rows.slice(headerIdx)).toEqual(input.slice(headerIdx));
  });

  it('works when the header is the first row (no preamble)', () => {
    const input = generateRevolutStatement({
      trades: [{ ticker: 'O', side: 'buy', quantity: 1.5, pricePerShare: 52, totalAmount: 78, date: '2025-01-15T13:30:00.000Z' }],
    });
    const { rows, replacements } = anonymizeBrokerRows(input, 'revolut');
    expect(rows).toEqual(input);
    expect(replacements.preambleCells).toBe(0);
  });

  it('scrubs an IBAN-shaped string in a table cell via the defensive sweep', () => {
    const input = revolutSampleRows();
    input.push(['2025-09-01T10:00:00.000Z', 'RO49AAAA1B31007593840000', 'CASH WITHDRAWAL', '', '', '-$10', 'USD', '1.08']);
    const { rows, replacements } = anonymizeBrokerRows(input, 'revolut');
    expect(rows[rows.length - 1][1]).toBe('[removed-iban]');
    // The preamble IBAN is wholesale-scrubbed to "[removed]" (not counted here);
    // only the table-cell IBAN goes through the targeted sweep.
    expect(replacements.ibans).toBe(1);
  });

  it('throws on a file with no recognizable Account Statement header', () => {
    expect(() => anonymizeBrokerRows([['Trade Date', 'Activity Type', 'Symbol', 'Amount']], 'revolut')).toThrow(
      /No Revolut Account Statement header/
    );
  });

  it('round-trip: the anonymized statement parses identically to the original', () => {
    const input = revolutSampleRows();
    const { rows } = anonymizeBrokerRows(input, 'revolut');
    const before = parseRevolutStatement(input);
    const after = parseRevolutStatement(rows);
    expect(before.transactions.length).toBeGreaterThan(0);
    expect(after).toEqual(before);
  });

  it('does not mutate the input rows', () => {
    const input = revolutSampleRows();
    const snapshot = JSON.parse(JSON.stringify(input));
    anonymizeBrokerRows(input, 'revolut');
    expect(input).toEqual(snapshot);
  });
});
