/**
 * Integration test: real Trading212 Annual Statement PDF fixture
 * → parse → calculate taxes with BNR rate → verify totals.
 *
 * Fixture: test-data/fixtures/annual-statement-2025-pages.json
 * Generated by: npx tsx test-data/extract-fixture.ts
 */
import { describe, it, expect } from 'vitest';
import { readFileSync } from 'fs';
import { join } from 'path';
import { parseTrading212AnnualStatement } from '../../parsers/trading212Pdf.js';
import { calculateTaxesFromPdf } from '../pdfTaxCalculator.js';
import { romaniaTaxConfig } from '../../taxRules/romania.js';

const fixturePath = join(__dirname, '../../../../test-data/fixtures/annual-statement-2025-pages.json');
const pageTexts: string[] = JSON.parse(readFileSync(fixturePath, 'utf8'));

const BNR_RATE_2025 = 4.7; // approximate average USD/RON for 2025

describe('PDF Integration: Annual Statement 2025', () => {
  const parsed = parseTrading212AnnualStatement(pageTexts);
  const { taxResult, securities } = calculateTaxesFromPdf(parsed, romaniaTaxConfig, BNR_RATE_2025);

  describe('parsing', () => {
    it('detects year 2025', () => {
      expect(parsed.year).toBe(2025);
    });

    it('parses all 7 sell trades', () => {
      expect(parsed.sellTrades).toHaveLength(7);
    });

    it('parses all 9 equity dividends', () => {
      expect(parsed.dividends).toHaveLength(9);
    });

    it('parses all 4 ETF distributions', () => {
      expect(parsed.distributions).toHaveLength(4);
    });

    it('produces no warnings', () => {
      expect(parsed.warnings).toHaveLength(0);
    });

    it('overview closed result matches sell trades sum', () => {
      const tradesSum = parsed.sellTrades.reduce((s, t) => s + t.totalResult, 0);
      expect(tradesSum).toBeCloseTo(parsed.overview.closedResult, 1);
    });

    it('overview gross dividends matches dividend + distribution sum', () => {
      const divSum = parsed.dividends.reduce((s, d) => s + d.grossAmountUsd, 0);
      const distSum = parsed.distributions.reduce((s, d) => s + d.grossAmountUsd, 0);
      expect(divSum + distSum).toBeCloseTo(parsed.overview.grossDividends, 0);
    });

    it('distributions have zero WHT (Ireland)', () => {
      for (const d of parsed.distributions) {
        expect(d.whtUsd).toBe(0);
      }
    });

    it('equity dividends have 10% WHT (US)', () => {
      for (const d of parsed.dividends) {
        expect(d.whtUsd).toBeGreaterThan(0);
        // WHT should be ~10% of gross
        const whtPct = d.whtUsd / d.grossAmountUsd;
        expect(whtPct).toBeCloseTo(0.1, 1);
      }
    });
  });

  describe('individual sell trades', () => {
    it('NVDA: 70 shares, gain $8,093.54', () => {
      const nvda = parsed.sellTrades.find(t => t.instrument === 'NVDA');
      expect(nvda).toBeDefined();
      expect(nvda!.positionSize).toBe(70);
      expect(nvda!.totalResult).toBeCloseTo(8093.54, 1);
    });

    it('PLTR: two trades totaling 270 shares, gain ~$31,198.80', () => {
      const pltrTrades = parsed.sellTrades.filter(t => t.isin === 'US69608A1088');
      expect(pltrTrades).toHaveLength(2);
      const totalShares = pltrTrades.reduce((s, t) => s + t.positionSize, 0);
      const totalResult = pltrTrades.reduce((s, t) => s + t.totalResult, 0);
      expect(totalShares).toBe(270);
      expect(totalResult).toBeCloseTo(31198.80, 0);
    });

    it('RGTI: two trades, near-zero net result', () => {
      const rgtiTrades = parsed.sellTrades.filter(t => t.isin === 'US76655K1034');
      expect(rgtiTrades).toHaveLength(2);
      const totalResult = rgtiTrades.reduce((s, t) => s + t.totalResult, 0);
      expect(totalResult).toBeCloseTo(20.93, 0);
    });
  });

  describe('tax calculation with rate 4.7', () => {
    it('capital gains: net gains ~192,458 RON', () => {
      expect(taxResult.capitalGains.netGains).toBeCloseTo(192458, 0);
    });

    it('capital gains tax: ~19,246 RON (10%)', () => {
      expect(taxResult.capitalGains.taxOwed).toBeCloseTo(19246, 0);
      expect(taxResult.capitalGains.taxRate).toBe(0.1);
    });

    it('gross dividends: ~662 RON', () => {
      expect(taxResult.dividends.grossTotal).toBeCloseTo(662, 0);
    });

    it('withholding tax paid: ~12 RON', () => {
      expect(taxResult.dividends.withholdingTaxPaid).toBeCloseTo(12, 0);
    });

    it('dividend tax owed: ~54 RON', () => {
      expect(taxResult.dividends.taxOwed).toBeCloseTo(54, 0);
    });

    it('CASS: 24x bracket (>97,200 RON), fixed 9,720 RON', () => {
      expect(taxResult.healthContribution.thresholdHit).toBe('24x');
      expect(taxResult.healthContribution.amountOwed).toBe(9720);
      expect(taxResult.healthContribution.totalNonSalaryIncome).toBeGreaterThan(97200);
    });

    it('total tax: ~29,020 RON', () => {
      expect(taxResult.totals.totalTaxOwed).toBeCloseTo(29020, 0);
    });

    it('early filing discount: ~579 RON (3% of income tax only, excludes CASS)', () => {
      const incomeTax = taxResult.capitalGains.taxOwed + taxResult.dividends.taxOwed;
      expect(taxResult.totals.earlyFilingDiscount).toBeCloseTo(incomeTax * 0.03, 0);
    });

    it('total after discount: ~28,441 RON', () => {
      const incomeTax = taxResult.capitalGains.taxOwed + taxResult.dividends.taxOwed;
      expect(taxResult.totals.totalAfterDiscount).toBeCloseTo(
        taxResult.totals.totalTaxOwed - incomeTax * 0.03, 0
      );
    });
  });

  describe('securities breakdown', () => {
    it('has 8 unique securities', () => {
      // NVDA, TSLA, PYPL, PLTR, RGTI (from trades) + GOOGL, META, VXUS (from dividends)
      expect(securities.length).toBe(8);
    });

    it('PLTR has highest realized gain', () => {
      const pltr = securities.find(s => s.isin === 'US69608A1088');
      expect(pltr).toBeDefined();
      expect(pltr!.realizedGainLoss).toBeCloseTo(31198.80 * BNR_RATE_2025, 0);
    });

    it('Vanguard S&P 500 has dividends but no trades', () => {
      const voo = securities.find(s => s.isin === 'IE00B3XXRP09');
      expect(voo).toBeDefined();
      expect(voo!.totalSoldShares).toBe(0);
      expect(voo!.totalDividends).toBeGreaterThan(0);
      expect(voo!.totalWithholdingTax).toBe(0); // Ireland distributions have 0 WHT
    });
  });
});
