/**
 * Integration test: real Trading212 Annual Statement PDF fixture
 * → parse → calculate taxes with BNR rate → verify totals.
 *
 * Fixture: test-data/fixtures/annual-statement-2025-pages.json
 * Generated by: npx tsx test-data/extract-fixture.ts
 */
import { describe, it, expect } from 'vitest';
import { readFileSync } from 'fs';
import { join } from 'path';
import { parseTrading212AnnualStatement } from '../../parsers/trading212Pdf.js';
import { calculateTaxesFromPdf } from '../pdfTaxCalculator.js';
import { romaniaTaxConfig } from '../../taxRules/romania.js';

const fixtureDir = join(__dirname, '../../../../test-data/fixtures');
const loadFixture = (name: string): string[] =>
  JSON.parse(readFileSync(join(fixtureDir, name), 'utf8'));

const pageTexts: string[] = loadFixture('annual-statement-2025-pages.json');

const BNR_RATE_2025 = 4.7; // approximate average USD/RON, used by single-rate fallback shapes below

// Real BNR USD/RON rates for tax year 2025, fetched from the prod
// /api/exchange-rates/2025/daily endpoint (248 business days, keys YYYY-MM-DD).
// Capital gains convert per-trade-date (art. 96); dividends use the annual
// average (art. 131 alin. 6).
const usdDaily2025: Record<string, number> = JSON.parse(
  readFileSync(join(fixtureDir, 'bnr-usd-2025-daily.json'), 'utf8'),
);
const USD_ANNUAL_AVG_2025 = 4.4705; // official BNR cursul mediu anual USD/RON 2025 (mean of monthly averages)

// Method (Codul Fiscal): capital gains convert at the per-trade-date BNR rate
// (art. 96); dividends + ETF distributions convert at BNR's official curs mediu
// anual (art. 131 alin. 6), which is the mean of the 12 MONTHLY averages = 4.4705
// USD/RON for 2025. Golden numbers use the real 2025 daily USD rates for the sells
// and 4.4705 for the dividends.
//
//   methodology                                 | total tax | after discount
//   --------------------------------------------|-----------|---------------
//   current: per-date sells + 4.4705 divs       | 28,500.69 |   27,937.27
//   prior code: per-date sells + 4.4645 divs    | 28,500.62 |   27,937.20  (daily-mean avg, fixed this PR)
//   all annual-avg 4.4645 (Dragos's filing)     | 28,052.89 |   27,502.90  <- filed D212 (28,053 lei, 10 Apr 2026)
//   flat 4.7 (original test)                    | 29,019.94 |   28,440.94
//
// The 4.4705 fix (this PR): BNR's official annual average is the mean of monthly
// averages, not the mean of all daily rates (4.4645). Only the dividend slice
// moves; the per-date capital gains are untouched, so total tax shifts +0.07 RON.
// Dragos's April 10, 2026 ANAF-accepted filing (28,053 lei) was made under the
// all-annual-average method and stands exactly as filed: a historical fact, not
// the engine's current output for the same statement.
describe('PDF Integration: Annual Statement 2025', () => {
  const parsed = parseTrading212AnnualStatement(pageTexts);
  const { taxResult, securities, warnings: engineWarnings } =
    calculateTaxesFromPdf(parsed, romaniaTaxConfig, USD_ANNUAL_AVG_2025, usdDaily2025);

  describe('parsing', () => {
    it('detects year 2025', () => {
      expect(parsed.year).toBe(2025);
    });

    it('parses all 7 sell trades', () => {
      expect(parsed.sellTrades).toHaveLength(7);
    });

    it('parses all 9 equity dividends', () => {
      expect(parsed.dividends).toHaveLength(9);
    });

    it('parses all 4 ETF distributions', () => {
      expect(parsed.distributions).toHaveLength(4);
    });

    it('produces no warnings', () => {
      expect(parsed.warnings).toHaveLength(0);
    });

    it('overview closed result matches sell trades sum', () => {
      const tradesSum = parsed.sellTrades.reduce((s, t) => s + t.totalResult, 0);
      expect(tradesSum).toBeCloseTo(parsed.overview.closedResult, 1);
    });

    it('overview gross dividends matches dividend + distribution sum', () => {
      const divSum = parsed.dividends.reduce((s, d) => s + d.grossAmountUsd, 0);
      const distSum = parsed.distributions.reduce((s, d) => s + d.grossAmountUsd, 0);
      expect(divSum + distSum).toBeCloseTo(parsed.overview.grossDividends, 0);
    });

    it('distributions have zero WHT (Ireland)', () => {
      for (const d of parsed.distributions) {
        expect(d.whtUsd).toBe(0);
      }
    });

    it('equity dividends have 10% WHT (US)', () => {
      for (const d of parsed.dividends) {
        expect(d.whtUsd).toBeGreaterThan(0);
        // WHT should be ~10% of gross
        const whtPct = d.whtUsd / d.grossAmountUsd;
        expect(whtPct).toBeCloseTo(0.1, 1);
      }
    });
  });

  describe('individual sell trades', () => {
    it('NVDA: 70 shares, gain $8,093.54', () => {
      const nvda = parsed.sellTrades.find(t => t.instrument === 'NVDA');
      expect(nvda).toBeDefined();
      expect(nvda!.positionSize).toBe(70);
      expect(nvda!.totalResult).toBeCloseTo(8093.54, 1);
    });

    it('PLTR: two trades totaling 270 shares, gain ~$31,198.80', () => {
      const pltrTrades = parsed.sellTrades.filter(t => t.isin === 'US69608A1088');
      expect(pltrTrades).toHaveLength(2);
      const totalShares = pltrTrades.reduce((s, t) => s + t.positionSize, 0);
      const totalResult = pltrTrades.reduce((s, t) => s + t.totalResult, 0);
      expect(totalShares).toBe(270);
      expect(totalResult).toBeCloseTo(31198.80, 0);
    });

    it('RGTI: two trades, near-zero net result', () => {
      const rgtiTrades = parsed.sellTrades.filter(t => t.isin === 'US76655K1034');
      expect(rgtiTrades).toHaveLength(2);
      const totalResult = rgtiTrades.reduce((s, t) => s + t.totalResult, 0);
      expect(totalResult).toBeCloseTo(20.93, 0);
    });
  });

  describe('tax calculation (per-trade-date BNR for capital gains, art. 96)', () => {
    // Golden numbers locked to the bani. See the re-baseline table above.
    it('capital gains: net gains 187,291.87 RON (per-trade-date conversion)', () => {
      expect(taxResult.capitalGains.netGains).toBeCloseTo(187291.87, 2);
    });

    it('capital gains tax: 18,729.19 RON (10%)', () => {
      expect(taxResult.capitalGains.taxOwed).toBeCloseTo(18729.19, 2);
      expect(taxResult.capitalGains.taxRate).toBe(0.1);
    });

    it('gross dividends: 629.45 RON (annual-average, art. 131 alin. 6)', () => {
      expect(taxResult.dividends.grossTotal).toBeCloseTo(629.45, 2);
    });

    it('withholding tax paid: 11.44 RON', () => {
      expect(taxResult.dividends.withholdingTaxPaid).toBeCloseTo(11.44, 2);
    });

    it('dividend tax owed: 51.50 RON', () => {
      expect(taxResult.dividends.taxOwed).toBeCloseTo(51.50, 2);
    });

    it('CASS: 24x bracket (>97,200 RON), fixed 9,720 RON', () => {
      expect(taxResult.healthContribution.thresholdHit).toBe('24x');
      expect(taxResult.healthContribution.amountOwed).toBe(9720);
      expect(taxResult.healthContribution.totalNonSalaryIncome).toBeGreaterThan(97200);
    });

    it('total tax: 28,500.69 RON', () => {
      expect(taxResult.totals.totalTaxOwed).toBeCloseTo(28500.69, 2);
    });

    it('early filing discount: 562.82 RON (3% of income tax only, excludes CASS)', () => {
      const incomeTax = taxResult.capitalGains.taxOwed + taxResult.dividends.taxOwed;
      expect(taxResult.totals.earlyFilingDiscount).toBeCloseTo(incomeTax * 0.03, 2);
    });

    it('total after discount: 27,937.27 RON', () => {
      expect(taxResult.totals.totalAfterDiscount).toBeCloseTo(27937.27, 2);
    });

    it('engine emits no sanity warnings (Dragos 2025 statement is internally consistent)', () => {
      expect(engineWarnings).toEqual([]);
    });
  });

  describe('securities breakdown', () => {
    it('has 8 unique securities', () => {
      // NVDA, TSLA, PYPL, PLTR, RGTI (from trades) + GOOGL, META, VXUS (from dividends)
      expect(securities.length).toBe(8);
    });

    it('PLTR has highest realized gain (per-trade-date: Feb sale @4.77 + Oct sale @4.33)', () => {
      const pltr = securities.find(s => s.isin === 'US69608A1088');
      expect(pltr).toBeDefined();
      // 13,159.95 USD @ 4.7728 (05.02.2025) + 18,038.85 USD @ 4.3258 (02.10.2025)
      expect(pltr!.realizedGainLoss).toBeCloseTo(140842.27, 1);
    });

    it('Vanguard S&P 500 has dividends but no trades', () => {
      const voo = securities.find(s => s.isin === 'IE00B3XXRP09');
      expect(voo).toBeDefined();
      expect(voo!.totalSoldShares).toBe(0);
      expect(voo!.totalDividends).toBeGreaterThan(0);
      expect(voo!.totalWithholdingTax).toBe(0); // Ireland distributions have 0 WHT
    });
  });
});

// Shape 2: Romanian-localized single-account RON. See docs/t212-pdf-formats.md.
describe('PDF Integration: RO single-account RON (Shape 2)', () => {
  const parsed = parseTrading212AnnualStatement(loadFixture('annual-statement-2025-ro-single-account.json'));
  const { taxResult, warnings: engineWarnings } = calculateTaxesFromPdf(parsed, romaniaTaxConfig, 1);

  describe('parsing', () => {
    it('detects year 2025 from Romanian header', () => {
      expect(parsed.year).toBe(2025);
    });

    it('detects RON as overview currency', () => {
      expect(parsed.overview.currency).toBe('RON');
    });

    it('parses Romanian overview labels', () => {
      expect(parsed.overview.closedResult).toBeCloseTo(30000, 2);
      expect(parsed.overview.grossDividends).toBeCloseTo(100, 2);
      expect(parsed.overview.taxWithheld).toBeCloseTo(10, 2);
    });

    it('parses one Romanian-language sell trade (Acțiune type)', () => {
      expect(parsed.sellTrades).toHaveLength(1);
      const trade = parsed.sellTrades[0];
      expect(trade.isin).toBe('ROHIELACNOR9');
      expect(trade.instrumentType).toMatch(/Acțiune/i);
      expect(trade.transactionCurrency).toBe('RON');
      expect(trade.totalResult).toBeCloseTo(30000, 2);
    });

    it('parses one US dividend', () => {
      expect(parsed.dividends).toHaveLength(1);
      const div = parsed.dividends[0];
      expect(div.isin).toBe('US0378331005');
      expect(div.grossAmountUsd).toBeCloseTo(100, 2);
      expect(div.whtUsd).toBeCloseTo(10, 2);
    });

    it('produces no parser warnings', () => {
      expect(parsed.warnings).toEqual([]);
    });
  });

  describe('tax calculation (exchangeRate=1, values already in RON)', () => {
    it('per-row sum used (RON trades match RON overview)', () => {
      expect(taxResult.capitalGains.netGains).toBeCloseTo(30000, 2);
    });

    it('capital gains tax: 3,000 RON', () => {
      expect(taxResult.capitalGains.taxOwed).toBeCloseTo(3000, 2);
    });

    it('dividend tax: 0 (WHT covers the 10%)', () => {
      expect(taxResult.dividends.taxOwed).toBe(0);
      expect(taxResult.dividends.withholdingTaxPaid).toBeCloseTo(10, 2);
    });

    it('CASS: 6x bracket (24,300 to 48,600 RON), fixed 2,430 RON', () => {
      expect(taxResult.healthContribution.thresholdHit).toBe('6x');
      expect(taxResult.healthContribution.amountOwed).toBe(2430);
    });

    it('total tax: 5,430 RON', () => {
      expect(taxResult.totals.totalTaxOwed).toBeCloseTo(5430, 2);
    });

    it('total after early-filing discount: 5,340 RON', () => {
      expect(taxResult.totals.totalAfterDiscount).toBeCloseTo(5340, 2);
    });

    it('engine emits no sanity warnings', () => {
      expect(engineWarnings).toEqual([]);
    });
  });
});

// Shape 3: post-Cyprus multi-account horizontal (Invest + CFD + Crypto).
// Mirrors Florin Pop 2026-05-24 PDF shape with anonymized identity.
// See docs/t212-pdf-formats.md.
describe('PDF Integration: post-Cyprus multi-account (Shape 3)', () => {
  const parsed = parseTrading212AnnualStatement(loadFixture('annual-statement-2025-multi-account.json'));
  const { taxResult, warnings: engineWarnings } = calculateTaxesFromPdf(parsed, romaniaTaxConfig, 1);

  describe('parsing', () => {
    it('detects year 2025', () => {
      expect(parsed.year).toBe(2025);
    });

    it('extracts Invest column closed result (leftmost), not CFD or Crypto', () => {
      expect(parsed.overview.closedResult).toBeCloseTo(3273.75, 2);
    });

    it('detects RON as overview currency from Invest column', () => {
      expect(parsed.overview.currency).toBe('RON');
    });

    it('extracts Invest column dividend fields, ignores CFD/Crypto siblings', () => {
      expect(parsed.overview.grossDividends).toBeCloseTo(332.34, 2);
      expect(parsed.overview.netDividends).toBeCloseTo(264.70, 2);
      expect(parsed.overview.taxWithheld).toBeCloseTo(67.63, 2);
    });

    it('parses 2 Invest sell trades summing to 3,273.75 RON', () => {
      expect(parsed.sellTrades).toHaveLength(2);
      const sum = parsed.sellTrades.reduce((s, t) => s + t.totalResult, 0);
      expect(sum).toBeCloseTo(3273.75, 2);
    });

    it('sell trades fall back to USD transactionCurrency (no standalone column in Cyprus format)', () => {
      // T212's Cyprus PDF omits the standalone currency column; the parser's
      // default fallback is 'USD'. This is the trigger condition for the
      // engine's overview-fallback branch.
      for (const trade of parsed.sellTrades) {
        expect(trade.transactionCurrency).toBe('USD');
      }
    });

    it('parses 2 US dividends summing to overview gross', () => {
      expect(parsed.dividends).toHaveLength(2);
      const gross = parsed.dividends.reduce((s, d) => s + d.grossAmountUsd, 0);
      expect(gross).toBeCloseTo(332.34, 2);
    });

    it('emits no "No Invest account section" warning (Invest is present)', () => {
      const investWarning = parsed.warnings.find(w => w.includes('No Invest account section'));
      expect(investWarning).toBeUndefined();
    });
  });

  describe('tax calculation (exchangeRate=1, overview in RON)', () => {
    it('engine falls back to overview.closedResult (trade USD != overview RON)', () => {
      // The trades parse with transactionCurrency='USD' but overview.currency='RON'.
      // matchesOverviewCurrency=false, so the engine uses overview.closedResult * 1.
      expect(taxResult.capitalGains.netGains).toBeCloseTo(3273.75, 2);
    });

    it('capital gains tax: 327.38 RON', () => {
      expect(taxResult.capitalGains.taxOwed).toBeCloseTo(327.38, 2);
    });

    it('dividend tax: 0 (WHT 67.63 covers gross tax 33.23)', () => {
      expect(taxResult.dividends.taxOwed).toBe(0);
      expect(taxResult.dividends.withholdingTaxPaid).toBeCloseTo(67.63, 2);
    });

    it('CASS: none bracket (3,606 RON total income < 24,300 threshold)', () => {
      expect(taxResult.healthContribution.thresholdHit).toBe('none');
      expect(taxResult.healthContribution.amountOwed).toBe(0);
    });

    it('total tax: 327.38 RON', () => {
      expect(taxResult.totals.totalTaxOwed).toBeCloseTo(327.38, 2);
    });

    it('total after early-filing discount: 317.55 RON', () => {
      expect(taxResult.totals.totalAfterDiscount).toBeCloseTo(317.55, 2);
    });

    it('engine sanity warnings stay silent under currency guard', () => {
      // The currency guard requires allSameCurrency AND matchesOverviewCurrency
      // before sign/magnitude checks fire. Here trades are all-USD (default)
      // and overview is RON, so the guard blocks the check and no warnings fire.
      // Florin's pre-PR-118 PDF tripped the warning because the parser had
      // picked the WRONG overview value (CFD's -226.80 instead of Invest's
      // +3273.75), making per-row vs overview disagree under the same currency.
      expect(engineWarnings).toEqual([]);
    });
  });
});

// Shape 4: ligature-broken labels. See docs/t212-pdf-formats.md.
describe('PDF Integration: ligature-broken labels (Shape 4)', () => {
  const parsed = parseTrading212AnnualStatement(loadFixture('annual-statement-2025-ligature-broken.json'));
  const { taxResult, warnings: engineWarnings } = calculateTaxesFromPdf(parsed, romaniaTaxConfig, BNR_RATE_2025);

  describe('parsing', () => {
    it('detects year 2025', () => {
      expect(parsed.year).toBe(2025);
    });

    it('overview.closedResult parses correctly (no ligature on this line)', () => {
      expect(parsed.overview.closedResult).toBeCloseTo(10000, 2);
    });

    it('overview.profit parses to 0 when label is ligature-broken (Pro\\tfi\\tt)', () => {
      // Engine does not depend on this field; the engine uses closedResult only.
      // Locking down the current behavior so a parser change that affects it
      // surfaces clearly.
      expect(parsed.overview.profit).toBe(0);
    });

    it('parses one sell trade and one dividend', () => {
      expect(parsed.sellTrades).toHaveLength(1);
      expect(parsed.dividends).toHaveLength(1);
    });

    it('produces no parser warnings', () => {
      // The ligature breaks adjacent to "profit"/"confirmation" labels do not
      // produce warnings because the parser cross-checks use closedResult and
      // grossAmountUsd (both unaffected by the ligature on this fixture).
      expect(parsed.warnings).toEqual([]);
    });
  });

  describe('tax calculation (BNR rate 4.7, USD trades + USD overview)', () => {
    it('capital gains netGains: 47,000 RON (10,000 USD * 4.7)', () => {
      expect(taxResult.capitalGains.netGains).toBeCloseTo(47000, 0);
    });

    it('CASS: 6x bracket (24,300 to 48,600 RON), fixed 2,430 RON', () => {
      expect(taxResult.healthContribution.thresholdHit).toBe('6x');
      expect(taxResult.healthContribution.amountOwed).toBe(2430);
    });

    it('total tax: 7,130 RON', () => {
      expect(taxResult.totals.totalTaxOwed).toBeCloseTo(7130, 0);
    });

    it('engine emits no sanity warnings (closedResult is internally consistent)', () => {
      expect(engineWarnings).toEqual([]);
    });
  });
});

// Shape 5: Real-customer Romanian multi-page with mixed transaction currencies.
// Source: Paul Adam's 2025 statement (consent given 2026-05-27, anonymized).
// Newer T212 Romanian header variant ("IDENTIFICARE CLIENT / NUMELE CLIENTULUI",
// "ID cont:"), 14 pages, single Trading 212 Invest account, RON base, mixed
// USD+EUR+RON sell-trade currencies, ligature-broken `Pro\tfi\tt` overview
// label. The PR #94 multi-page section continuation bug is the original
// regression case; with that fix in place, this fixture exercises the full
// integration path end-to-end.
//
// Per-row sum (~30.75 RON-equivalent across mixed currencies) disagrees with
// overview closed result (-365.58 RON), which is the expected behavior when
// the parser refuses to mix currencies and the engine falls back to overview.
describe('PDF Integration: real-customer Romanian multi-page mixed-currency (Shape 5)', () => {
  const parsed = parseTrading212AnnualStatement(loadFixture('annual-statement-2025-multi-page.json'));
  const { taxResult, warnings: engineWarnings } = calculateTaxesFromPdf(parsed, romaniaTaxConfig, 1);

  describe('parsing', () => {
    it('detects year 2025', () => {
      expect(parsed.year).toBe(2025);
    });

    it('processes all 14 pages without throwing', () => {
      // The PR #94 regression: pre-fix, multi-page section continuation lost
      // sell trades + dividends silently. With the fix, the parser reads
      // through all 14 pages and collects rows from continuation pages.
      expect(parsed.sellTrades.length).toBeGreaterThan(100);
      expect(parsed.dividends.length).toBeGreaterThan(40);
    });

    it('parses 144 sell trades across multi-page section continuation', () => {
      expect(parsed.sellTrades).toHaveLength(144);
    });

    it('parses 49 dividends across multi-page section continuation', () => {
      expect(parsed.dividends).toHaveLength(49);
    });

    it('overview currency is RON (Romanian-localized statement)', () => {
      expect(parsed.overview.currency).toBe('RON');
    });

    it('overview closed result reflects the net loss (-365.58 RON)', () => {
      expect(parsed.overview.closedResult).toBeCloseTo(-365.58, 2);
    });

    it('overview dividends parse: gross 93.70 RON, net 85.97 RON, WHT 7.74 RON', () => {
      expect(parsed.overview.grossDividends).toBeCloseTo(93.70, 2);
      expect(parsed.overview.netDividends).toBeCloseTo(85.97, 2);
      expect(parsed.overview.taxWithheld).toBeCloseTo(7.74, 2);
    });

    it('overview profit parses to 0 due to ligature-broken `Pro\\tfi\\tt` label', () => {
      // Shape 4 behavior reproduced naturally in Paul's real PDF: the `fi`
      // ligature splits during PDF text extraction. Engine does not depend on
      // overview.profit; it uses overview.closedResult only.
      expect(parsed.overview.profit).toBe(0);
    });

    it('sell trades cover mixed transaction currencies (USD, EUR, RON)', () => {
      const currencies = new Set(parsed.sellTrades.map((t) => t.transactionCurrency));
      expect(currencies.has('USD')).toBe(true);
      expect(currencies.has('EUR')).toBe(true);
      expect(currencies.has('RON')).toBe(true);
    });

    it('emits parser warning when per-row sum disagrees with overview (mixed-currency case)', () => {
      // Per-row sum (~30.75 RON-equivalent, mostly meaningless across mixed
      // currencies) vs overview closedResult (-365.58 RON, authoritative)
      // disagrees by sign + magnitude. The parser surfaces this to the UI
      // banner; the engine falls back to overview.
      expect(parsed.warnings.length).toBeGreaterThanOrEqual(1);
      expect(parsed.warnings.some((w) => w.includes('per-row sum') && w.includes('overview'))).toBe(true);
    });
  });

  describe('tax calculation (exchangeRate=1, overview in RON)', () => {
    it('engine falls back to overview.closedResult (mixed transaction currencies)', () => {
      // allSameCurrency=false (USD+EUR+RON) → engine uses overview, which
      // is a net loss in RON. Loss → netGains=0 (no negative tax).
      expect(taxResult.capitalGains.netGains).toBe(0);
    });

    it('capital gains tax: 0 RON (loss)', () => {
      expect(taxResult.capitalGains.taxOwed).toBe(0);
    });

    it('gross dividends: 93.70 RON (overview * exchangeRate)', () => {
      expect(taxResult.dividends.grossTotal).toBeCloseTo(93.70, 2);
    });

    it('dividend tax owed: ~1.6 RON (gross 9.37 minus WHT 7.74)', () => {
      // Hand-computed: 93.70 * 10% = 9.37, minus WHT 7.74 → 1.63 RON.
      // Engine emits 1.64 due to per-row rounding; precision 1 covers both.
      expect(taxResult.dividends.taxOwed).toBeCloseTo(1.6, 1);
    });

    it('withholding tax credited: ~7.74 RON (overview)', () => {
      expect(taxResult.dividends.withholdingTaxPaid).toBeCloseTo(7.74, 1);
    });

    it('CASS: none bracket (net income well below 24,300 RON threshold)', () => {
      // Capital gains 0 (loss) + gross dividends 93.70 RON = far below 24,300.
      expect(taxResult.healthContribution.thresholdHit).toBe('none');
      expect(taxResult.healthContribution.amountOwed).toBe(0);
    });

    it('total tax owed: ~1.6 RON (dividends only)', () => {
      expect(taxResult.totals.totalTaxOwed).toBeCloseTo(1.6, 1);
    });

    it('engine sanity warnings stay silent (mixed-currency guard blocks the check)', () => {
      // Currency guard: allSameCurrency must be true for sign/magnitude check
      // to fire. Paul has USD+EUR+RON, so guard returns early.
      expect(engineWarnings).toEqual([]);
    });
  });
});

// Shape 6: Real-customer English full multi-account statement.
// Source: Florin Pop's 2025 statement (consent given 2026-05-27, anonymized).
// English, Cyprus footer, 21 pages, three Trading 212 accounts (Invest + CFD +
// Crypto) in horizontal layout on the overview page, RON base for Invest+CFD,
// EUR for Crypto. The PR #118 multi-account horizontal-layout bug is the
// original regression case; with that fix in place, this fixture exercises
// the full real-PDF integration path with all 21 pages of sell trades and
// dividends.
//
// Versus the synthetic Shape 3 (3-page minimal repro): same financial overview
// (3,273.75 / 264.70 / 332.34 / 67.63), but exercises the full real-statement
// page count + multi-page continuation + Cyprus boilerplate text + English
// localization end-to-end.
describe('PDF Integration: real-customer full multi-account (Shape 6)', () => {
  const parsed = parseTrading212AnnualStatement(loadFixture('annual-statement-2025-multi-account-full.json'));
  const { taxResult, warnings: engineWarnings } = calculateTaxesFromPdf(parsed, romaniaTaxConfig, 1);

  describe('parsing', () => {
    it('detects year 2025', () => {
      expect(parsed.year).toBe(2025);
    });

    it('processes all 21 pages without throwing', () => {
      expect(parsed.sellTrades.length).toBeGreaterThan(100);
      expect(parsed.dividends.length).toBeGreaterThan(10);
    });

    it('extracts Invest column closed result (leftmost), not CFD or Crypto', () => {
      // CFD sits at +RON -226.80, Crypto at €0.00. Parser must select Invest's
      // +3,273.75 RON (leftmost overview block).
      expect(parsed.overview.closedResult).toBeCloseTo(3273.75, 2);
    });

    it('detects RON as overview currency from Invest column', () => {
      expect(parsed.overview.currency).toBe('RON');
    });

    it('extracts Invest column dividend fields, ignores CFD/Crypto siblings', () => {
      expect(parsed.overview.grossDividends).toBeCloseTo(332.34, 2);
      expect(parsed.overview.netDividends).toBeCloseTo(264.70, 2);
      expect(parsed.overview.taxWithheld).toBeCloseTo(67.63, 2);
    });

    it('parses 228 Invest sell trades summing to 3,273.75 RON', () => {
      expect(parsed.sellTrades).toHaveLength(228);
      const sum = parsed.sellTrades.reduce((s, t) => s + t.totalResult, 0);
      expect(sum).toBeCloseTo(3273.75, 2);
    });

    it('parses 26 dividends across multi-page section continuation', () => {
      expect(parsed.dividends).toHaveLength(26);
    });

    it('sell trades fall back to USD transactionCurrency (no standalone column in Cyprus format)', () => {
      // T212's Cyprus PDF omits the standalone currency column; parser default
      // is 'USD'. This is the trigger for the engine's overview-fallback branch.
      for (const trade of parsed.sellTrades) {
        expect(trade.transactionCurrency).toBe('USD');
      }
    });

    it('produces no parser warnings (Invest section is consistent)', () => {
      expect(parsed.warnings).toEqual([]);
    });
  });

  describe('tax calculation (exchangeRate=1, overview in RON)', () => {
    it('engine falls back to overview.closedResult (trade USD != overview RON)', () => {
      // matchesOverviewCurrency=false (trades USD, overview RON), so the
      // engine uses overview.closedResult * 1.
      expect(taxResult.capitalGains.netGains).toBeCloseTo(3273.75, 2);
    });

    it('capital gains tax: 327.38 RON (3,273.75 * 10%)', () => {
      // Hand-computed: 3,273.75 * 0.10 = 327.375 → 327.38 to 2 decimals.
      expect(taxResult.capitalGains.taxOwed).toBeCloseTo(327.38, 2);
    });

    it('dividend tax: 0 (WHT 67.63 covers gross tax 33.23)', () => {
      // Hand-computed: 332.34 * 10% = 33.23 RON owed; WHT 67.63 RON credit
      // already paid → max(0, 33.23 - 67.63) = 0.
      expect(taxResult.dividends.taxOwed).toBe(0);
      expect(taxResult.dividends.withholdingTaxPaid).toBeCloseTo(67.63, 2);
    });

    it('CASS: none bracket (3,606 RON total income < 24,300 threshold)', () => {
      // 3,273.75 capital gains + 332.34 gross dividends = 3,606.09 RON. Below
      // the 24,300 RON 6x bracket entry.
      expect(taxResult.healthContribution.thresholdHit).toBe('none');
      expect(taxResult.healthContribution.amountOwed).toBe(0);
    });

    it('total tax: 327.38 RON', () => {
      expect(taxResult.totals.totalTaxOwed).toBeCloseTo(327.38, 2);
    });

    it('total after early-filing discount: ~317.55 RON (3% off)', () => {
      // Hand-computed: 327.38 - (327.38 * 0.03) = 327.38 - 9.82 = 317.56.
      // Engine emits 317.55 due to per-component rounding; precision 1 covers.
      expect(taxResult.totals.totalAfterDiscount).toBeCloseTo(317.55, 1);
    });

    it('engine sanity warnings stay silent under currency guard', () => {
      // allSameCurrency=true (all USD) AND matchesOverviewCurrency=false
      // (USD != RON) → guard requires both, so check does not fire.
      expect(engineWarnings).toEqual([]);
    });
  });
});
